# Generated by Django 2.2 on 2019-04-22 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_cobro', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2019, 4, 22, 21, 42, 46, 703401, tzinfo=utc))),
                ('diasFestivos', models.DateField()),
            ],
        ),
    ]
