# Generated by Django 2.2 on 2019-04-22 22:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrodiasfestivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 22, 6, 28, 415877, tzinfo=utc)),
        ),
    ]
