# Generated by Django 2.2 on 2019-04-23 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registrodiasfestivos', '0002_auto_20190422_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 21, 18, 10, 141969, tzinfo=utc)),
        ),
    ]
